version: '3.3'
services:
  registry:
    container_name: docker_registry
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - docker-registry:/data
      - ./certs:/data/certs
      - ./auth:/data/auth
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data/registry_data
      REGISTRY_HTTP_TLS_CERTIFICATE: /data/certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /data/certs/domain.key
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /data/auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm

  registry-ui:
    image: parabuzzle/craneoperator:latest
    ports:
      - "8086:80"
    environment:
      REGISTRY_HOST: 10.0.9.65
      REGISTRY_PORT: 5000
      REGISTRY_PROTOCOL: https
      SSL_VERIFY: "false"
      REGISTRY_ALLOW_DELETE: "true"
      REGISTRY_USERNAME: admin
      REGISTRY_PASSWORD: admin
      USERNAME: admin
      PASSWORD: admin
    restart: always
    depends_on:
      - registry

volumes:
  docker-registry:
    external: yes